USE [master]
GO

/****** Object:  Database [restaurante]    Script Date: 9/12/2022 00:10:06 ******/
CREATE DATABASE [restaurante]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'restaurante', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\restaurante.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'restaurante_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\restaurante_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [restaurante].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [restaurante] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [restaurante] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [restaurante] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [restaurante] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [restaurante] SET ARITHABORT OFF 
GO

ALTER DATABASE [restaurante] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [restaurante] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [restaurante] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [restaurante] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [restaurante] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [restaurante] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [restaurante] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [restaurante] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [restaurante] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [restaurante] SET  DISABLE_BROKER 
GO

ALTER DATABASE [restaurante] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [restaurante] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [restaurante] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [restaurante] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [restaurante] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [restaurante] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [restaurante] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [restaurante] SET RECOVERY FULL 
GO

ALTER DATABASE [restaurante] SET  MULTI_USER 
GO

ALTER DATABASE [restaurante] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [restaurante] SET DB_CHAINING OFF 
GO

ALTER DATABASE [restaurante] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [restaurante] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [restaurante] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [restaurante] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [restaurante] SET QUERY_STORE = OFF
GO

ALTER DATABASE [restaurante] SET  READ_WRITE 
GO

